services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    network_mode: "host"
    volumes:
      - data:/var/lib/postgresql/data

  migrate:
    build:
      context: database
      dockerfile: Dockerfile.migrate
    environment:
      DATABASE_URL: postgres://postgres@localhost/postgres?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
    network_mode: "host"
    depends_on:
      - postgres

  crawler:
    build:
      context: crawler
      dockerfile: Dockerfile
    environment:
      CRAWLER_ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      CRAWLER_DATABASE_URL: postgres://postgres@localhost/postgres?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
    network_mode: "host"
    depends_on:
      - migrate

volumes:
  data:
